Life improvement: Use nav.html and load with nav.js
diyhrt/diyhrt.github.io pull request #6
Opened 2022-08-11 09:22 UTC by milktea02

I saw #3 and #4 and figured I'd try find a way to simplify the nav bar generation that might be easy to understand and maintain.

**Proposed change:**
- Store the sidebar items in `nav.html`
- Load `nav.html` into each page using `nav.js` script
- Based on this stackoverflow  solution  using pure html and javascript
  - https://stackoverflow.com/a/68909928/5814222

**Why?**
- Easier to change on `nav.html` document than copy past across all your html files

**Testing:**
- You'll likely need to enable CORS if running on chrome (and possibly other browsers?) or start a simple http server
  - Why? Because when running locally for testing, `nav.html` is coming from your filesystem (eg. `file://localhost/path/to/nav`) which is different from `index.html` which loads on your browser as `localhost/path/to/index.hml` and your browser thinks that's shady
  - You can use chrome extension to run an http server (https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb/)
  - or if you're familiar with the terminal and python you can use `python -m http.server`

Tada!
<img width="350" alt="image" src="https://user-images.githubusercontent.com/5224106/184101905-1d70bbef-1b2c-41af-9d1b-6308a4e18a98.png">

2022-08-11 09:33 UTC, 5HT2 commented
Do we already use JS? I'd rather not use JS in a static site that doesn't use any. 

Using a shared file isn't a bad idea - I was in the process of setting up templating for i18n and it wouldn't be hard to split components into parts.

2022-08-29 01:01 UTC, solonovamax commented
If you wanted to do templating, you could consider something like how I have [my site](https://solonovamax.gay) set up ([source code](https://github.com/solonovamax/solonovamax.gay/))

Basically, I have a couple of thymeleaf templates set up (that inherit from some layout templates), which will inject markdown files into the html. That way, I can write content in markdown, and then it will be injected into the site when requested by a user. (It is cached after the first request, to avoid long load times. Caching can be disabled for development)

My site is written entirely without a single line of js (I hate it with a passion), so you don't have to worry about that. It's 100% server side.

Also, I have a few other fancy things, like emojis in markdown (using custom flexmark extension to allow for arbitrary new emojis not in the original spec), a config file for loading contact links, and split frontend/backend so that they can be updated independently

2022-09-07 20:46 UTC, 5HT2 commented
> My site is written entirely without a single line of js (I hate it with a passion), so you don't have to worry about that. It's 100% server side.

I feel similarly, though I would've setup templating by now if this wasn't entirely static. I would prefer QTC templates and have a github action to do the static generation after a push? Honestly a pain in the ass to setup regardless, but eventually more ideal than what we have going on or a non-serverless solution.

2022-09-07 20:47 UTC, 5HT2 commented
@milktea02

Sorry for the incredibly late reply - I've been on vacation for a few weeks and was just able to get back to this.

Would you mind rebasing to the main branch and fixing the conflicts? I'll be free to look over it whenever (any hours outside of 09:00 to 15:00 PDT).

2022-09-07 21:16 UTC, milktea02 commented
@5HT2 

ah sorry, I've also been MIA - I will try get the rebase done this week


As for earlier questions/comments: 

I agree, the website wouldn't be fully static with the addition of JS. I also prefer templated solutions but as mentioned already, the site is already fully static so this seemed to be a less invasive solution.

Feel free to disregard this PR if it's not in the direction the maintainers prefer.

2022-09-08 00:22 UTC, 5HT2 commented
I don't mind JS being used for this, please feel free to rebase onto the main branch and fix the PR to be mergeable, it would be greatly appreciated :)

2022-09-11 23:15 UTC, 5HT2 requested changes

2022-09-11 23:15 UTC, 5HT2 commented on nav.js
> +    oldelem.parentNode.replaceChild(newelem,oldelem);
snakeCase for these please, I'll fix it myself

2022-09-11 23:19 UTC, 5HT2 approved these changes
Thanks, looks good to me!

2022-09-11 23:19 UTC, merged